export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bec9c8",
        "primary-container": "#006a6a",
        "on-secondary": "#ffffff",
        "background": "#f7faf9",
        "primary-fixed-dim": "#84d4d3",
        "on-tertiary-fixed": "#001e2e",
        "tertiary-container": "#2b6485",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#98cdf2",
        "on-secondary-container": "#316e52",
        "surface-tint": "#006a6a",
        "surface-variant": "#e0e3e2",
        "on-tertiary": "#ffffff",
        "surface-dim": "#d7dbda",
        "tertiary-fixed": "#c7e7ff",
        "secondary-container": "#aeeecb",
        "on-secondary-fixed-variant": "#0e5138",
        "surface-container-low": "#f1f4f3",
        "secondary-fixed": "#b1f0ce",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#002114",
        "surface-container": "#ebeeed",
        "surface-bright": "#f7faf9",
        "on-tertiary-container": "#b3deff",
        "on-primary-fixed": "#002020",
        "secondary": "#2c694e",
        "on-primary-container": "#97e7e6",
        "inverse-primary": "#84d4d3",
        "on-tertiary-fixed-variant": "#064c6b",
        "inverse-surface": "#2d3131",
        "surface-container-highest": "#e0e3e2",
        "error": "#ba1a1a",
        "primary-fixed": "#a0f0f0",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "primary": "#005050",
        "secondary-fixed-dim": "#95d4b3",
        "inverse-on-surface": "#eef1f0",
        "outline": "#6e7979",
        "on-surface-variant": "#3e4948",
        "on-primary-fixed-variant": "#004f4f",
        "surface": "#f7faf9",
        "on-surface": "#181c1c",
        "tertiary": "#064c6c",
        "on-background": "#181c1c",
        "surface-container-high": "#e6e9e8"
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}
